apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - config.yaml
  name: order-service-configmap

resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/valentinlutz/order-service
  newName: ghcr.io/valentinlutz/order-service
  newTag: latest
