# Global config
region: NONE
environment: CONTAINER

# Server config
server:
  port: 8443
  certificate_path: config/app.crt
  key_path: config/app.key

# Logger config
logger:
  level: INFO
  json: false

# Database config
database:
  host: postgresql
  port: 5432
  user: test
  password: test
  database: test
  max_idle_connections: 10
  max_open_connections: 100
