# Global config
region: NONE
environment: DEV

# Server config
server:
  port: 10443
  certificate_path: config/app.public.none-dev.crt
  key_path: config/app.private.none-dev.key

# Logger config
logger:
  level: DEBUG

# Database config
database:
  host: database-postgres
  port: 5432
  user: test
  password: test
  database: test
  max_idle_connections: 4
  max_open_connections: 8
  max_idle_time: 5m
  max_lifetime: 1h
