VERSION 0.6
FROM golang:1.19.0-alpine3.16
WORKDIR /build

dependencies:
    COPY ../../libraries/errors+artifact/* /libraries/errors
    COPY go.mod go.sum ./
    RUN go mod download

artifact:
    FROM +dependencies
    COPY response_helper.go ./
    SAVE ARTIFACT .