# Global config
region: NONE
environment: LOCAL

# Server config
server:
  port: 8443
  certificate_path: config/app.crt
  key_path: config/app.key

# Logger config
logger:
  level: DEBUG
  json: false

# Database config
database:
  host: localhost
  port: 9432
  user: "test"
  password: "test"
  database: "dev_db"
  max_idle_connections: 10
  max_open_connections: 90
