version: '3.9'

networks:
  default:
    name: order-service

services:
  postgresql:
    image: postgres:14.2
    container_name: postgres
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '9432:5432'
