apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: order-service
    spec:
      volumes:
        - name: order-service-configmap-volume
          configMap:
            name: order-service-configmap
      containers:
        - name: order-service
          image: ghcr.io/valentinlutz/order-service:latest
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: order-service-configmap-volume
              subPath: config.yaml
              mountPath: /app/config/config.yaml
          resources:
            limits:
              cpu: "1"
              memory: 100Mi