apiVersion: v1
kind: Service
metadata:
  name: order-service-service
  labels:
    app: order-service
spec:
  ports:
    - name: https
      targetPort: 8443
      port: 433
  selector:
    app: order-service