version: '3.9'

networks:
  default:
    name: order-service

services:
  app:
    image: ghcr.io/valentinlutz/order-service:latest
    build:
      context: ../../../
      dockerfile: ./services/order/app/Dockerfile
    container_name: app
    volumes:
      - ../config/app/config.none-container.yaml:/app/config/config.yaml:ro
      - ../config/app.crt:/app/config/app.crt:ro
      - ../config/app.key:/app/config/app.key:ro
    ports:
      - '9443:8443'

  prometheus:
    image: prom/prometheus:v2.40.6
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:9.3.1
    container_name: grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ./grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json:ro
    ports:
      - '9000:3000'
