global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: postgres-exporter
    static_configs:
      - targets: ["localhost:9187"]
  - job_name: app
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /status/metrics
    static_configs:
      - targets: ["localhost:10443"]
