{
 "title": "metrics",
 "description": "Go application runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method, route) (rate(app_http_server_request_duration_seconds_sum[$__rate_interval])) / sum by (method, route) (rate(app_http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{mehtod}}{{route}}"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"app\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "99 Percentile Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, method, route) (rate(app_http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Number of Heap Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"app\"} - go_memstats_frees_total{job=\"app\"}"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(method, route) (rate(app_http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{mehtod}} {{route}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"app\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Average Garbage Collection Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"app\"}[$__rate_interval]) / rate(go_gc_duration_seconds_count{job=\"app\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Off-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=\"app\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"app\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"app\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"app\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"app\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"app\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"$job\", instance=~\"$instance\"} - go_memstats_other_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {instance={{instance}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"app\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"app\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"app\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"app\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"app\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"app\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"app\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"app\"}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=\"app\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"app\"}[1m])"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"app\"}[1m])"
    }
   ]
  }
 ]
}