{
 "title": "metrics",
 "description": "Go application runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Number of Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of Heap Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"$job\"} - go_memstats_frees_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(namespace_http_server_request_duration_seconds_bucket[$__rate_interval])) by (le, method, route))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Number of Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(method, route) (rate(namespace_http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"$job\", instance=~\"$instance\"} - go_memstats_other_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {instance={{instance}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  }
 ]
}