version: 0.1
default:
  global:
    parameters:
      stack_name: facts-lambda
  build:
    parameters:
      cached: true
      parallel: true
  deploy:
    parameters:
      capabilities:
        - CAPABILITY_IAM
      confirm_changeset: true
  sync:
    parameters:
      watch: true
  local_start_lambda:
    parameters:
      warm_containers: EAGER