version: '3.8'
services:
  postgres:
    image: postgres:15.2-alpine3.17
    container_name: postgres
    network_mode: host
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
