version: '3.8'
services:
  postgres:
    image: postgres:15.2-alpine3.17
    container_name: postgres
    network_mode: host
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    network_mode: host
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    network_mode: host
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ./grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json:ro