#on:
#  push:
#
#jobs:
#  create-version:
#    runs-on: ubuntu-latest
#    env:
#      BRANCH: ${{ github.ref_name }}
#    outputs:
#      version: ${{ steps.create.outputs.version }}
#    steps:
#      - name: Create project version
#        id: create
#        run: |
#          if [ 'master' == "$BRANCH"  ]
#          then
#            echo "version=$(date +"%y.%m.%d.%H%M%S")" >> $GITHUB_OUTPUT
#          else
#            echo "version=$(date +"%y.%m.%d.%H%M%S")-SNAPSHOT" >> $GITHUB_OUTPUT
#          fi
#
#  build-order-service:
#    uses: ./.github/workflows/build-go-app.yaml
#    needs:
#      - create-version
#    with:
#      app-path: ./go/services/order
#      version: ${{ needs.create-version.outputs.version }}
#      src: |
#        src:
#          - 'go/go.mod'
#          - 'go/go.sum'
#          - 'go/libraries/**'
#          - 'go/services/order/**'
#
#    secrets: inherit