on:
  workflow_call:
    inputs:
      app-path:
        required: true
        type: string
      version:
        required: true
        type: string
      src:
        required: true
        type: string

jobs:
  build-app:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        working-directory: ${{ inputs.app-path }}
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_REPOSITORY: valentinlutz
      VERSION: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: ${{ inputs.src }}

      - name: Set up GO
        if: steps.changes.outputs.src == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.2'
          cache: true
          cache-dependency-path: go/go.sum

      - name: Run unit tests
        if: steps.changes.outputs.src == 'true'
        run: make test.unit

      - name: Run golangci-lint
        if: steps.changes.outputs.src == 'true'
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          working-directory: ${{ inputs.app-path }}/app
          skip-pkg-cache: true

      - name: Build the container image
        if: steps.changes.outputs.src == 'true'
        run: make docker.build

      - name: Login to GitHub container registry
        if: steps.changes.outputs.src == 'true'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the container image
        if: steps.changes.outputs.src == 'true'
        run: make docker.push